<?php

namespace ContainerQMPYmxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N8YG42MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N8YG42M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N8YG42M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'phone' => ['privates', '.errored..service_locator.N8YG42M.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.N8YG42M": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".'],
            'phoneRepository' => ['privates', 'App\\Repository\\PhoneRepository', 'getPhoneRepositoryService', true],
        ], [
            'phone' => 'App\\Entity\\Phone',
            'phoneRepository' => 'App\\Repository\\PhoneRepository',
        ]);
    }
}
