<?php

namespace ContainerQMPYmxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__NayvvWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..nayvvW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..nayvvW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator..nayvvW.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator..nayvvW": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'student' => 'App\\Entity\\Student',
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);
    }
}
