<?php

namespace ContainerQMPYmxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TpYa4R8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TpYa4R8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TpYa4R8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campusRepository' => ['privates', 'App\\Repository\\CampusRepository', 'getCampusRepositoryService', true],
        ], [
            'campusRepository' => 'App\\Repository\\CampusRepository',
        ]);
    }
}
