<?php

namespace ContainerQMPYmxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LU8QvKjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LU8QvKj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LU8QvKj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'phone' => ['privates', '.errored..service_locator.LU8QvKj.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.LU8QvKj": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phone' => 'App\\Entity\\Phone',
        ]);
    }
}
