<?php

namespace ContainerQMPYmxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JLfvEBiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jLfvEBi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jLfvEBi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campus' => ['privates', '.errored..service_locator.jLfvEBi.App\\Entity\\Campus', NULL, 'Cannot autowire service ".service_locator.jLfvEBi": it needs an instance of "App\\Entity\\Campus" but this type has been excluded in "config/services.yaml".'],
        ], [
            'campus' => 'App\\Entity\\Campus',
        ]);
    }
}
