<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4GyvClb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4GyvClb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4GyvClb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4GyvClb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4GyvClb\App_KernelDevDebugContainer([
    'container.build_hash' => '4GyvClb',
    'container.build_id' => '5854db63',
    'container.build_time' => 1681676525,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4GyvClb');
