<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEK3VQfA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEK3VQfA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEK3VQfA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEK3VQfA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEK3VQfA\App_KernelDevDebugContainer([
    'container.build_hash' => 'EK3VQfA',
    'container.build_id' => '98f9401e',
    'container.build_time' => 1679047102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEK3VQfA');
