<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ6rmH5k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ6rmH5k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ6rmH5k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ6rmH5k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ6rmH5k\App_KernelDevDebugContainer([
    'container.build_hash' => 'J6rmH5k',
    'container.build_id' => '8e3cb558',
    'container.build_time' => 1681486389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ6rmH5k');
