<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_band_index' => [[], ['_controller' => 'App\\Controller\\BandController::index'], [], [['text', '/band/']], [], [], []],
    'app_band_new' => [[], ['_controller' => 'App\\Controller\\BandController::new'], [], [['text', '/band/new']], [], [], []],
    'app_band_show' => [['id'], ['_controller' => 'App\\Controller\\BandController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band']], [], [], []],
    'app_band_edit' => [['id'], ['_controller' => 'App\\Controller\\BandController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/band']], [], [], []],
    'app_band_delete' => [['id'], ['_controller' => 'App\\Controller\\BandController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band']], [], [], []],
    'app_band_member_index' => [[], ['_controller' => 'App\\Controller\\BandMemberController::index'], [], [['text', '/band/member/']], [], [], []],
    'app_band_member_new' => [[], ['_controller' => 'App\\Controller\\BandMemberController::new'], [], [['text', '/band/member/new']], [], [], []],
    'app_band_member_show' => [['id'], ['_controller' => 'App\\Controller\\BandMemberController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band/member']], [], [], []],
    'app_band_member_edit' => [['id'], ['_controller' => 'App\\Controller\\BandMemberController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/band/member']], [], [], []],
    'app_band_member_delete' => [['id'], ['_controller' => 'App\\Controller\\BandMemberController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band/member']], [], [], []],
];
