<?php

namespace ContainerRQZ8hYn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ONpgZxmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ONpgZxm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ONpgZxm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'make' => ['privates', '.errored..service_locator.ONpgZxm.App\\Entity\\Make', NULL, 'Cannot autowire service ".service_locator.ONpgZxm": it needs an instance of "App\\Entity\\Make" but this type has been excluded in "config/services.yaml".'],
            'makeRepository' => ['privates', 'App\\Repository\\MakeRepository', 'getMakeRepositoryService', true],
        ], [
            'make' => 'App\\Entity\\Make',
            'makeRepository' => 'App\\Repository\\MakeRepository',
        ]);
    }
}
