<?php

namespace ContainerRQZ8hYn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C3f93BlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C3f93Bl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C3f93Bl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campus' => ['privates', '.errored..service_locator.C3f93Bl.App\\Entity\\Campus', NULL, 'Cannot autowire service ".service_locator.C3f93Bl": it needs an instance of "App\\Entity\\Campus" but this type has been excluded in "config/services.yaml".'],
            'campusRepository' => ['privates', 'App\\Repository\\CampusRepository', 'getCampusRepositoryService', true],
        ], [
            'campus' => 'App\\Entity\\Campus',
            'campusRepository' => 'App\\Repository\\CampusRepository',
        ]);
    }
}
