<?php

namespace ContainerRQZ8hYn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C3f93Bl.App\Entity\Campus' shared service.
     *
     * @return \App\Entity\Campus
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.C3f93Bl": it needs an instance of "App\\Entity\\Campus" but this type has been excluded in "config/services.yaml".');
    }
}
